#!/bin/sh
set -eu

# shellcheck disable=SC1091
. ./lib/expect.sh

if [ ! -d .cache/test ]
then
    printf '%s\n' 'test/test-cat: .cache/test does not exist' >&2
    exit 1
fi

expect_output abc "$(.cache/dud-sh --cat -c abc)" 'argument source cat'
expect_output '' "$(.cache/dud-sh --cat -c '')" 'empty argument source cat'
expect_output abc "$(printf abc | .cache/dud-sh --cat -)" 'stdin cat'

printf 'hello' >.cache/test/cat-normal
expect_output hello "$(.cache/dud-sh --cat .cache/test/cat-normal)" 'file cat'

printf 'dash' >.cache/test/-cat-dash
dash_output=$(
    cd .cache/test
    ../dud-sh --cat -- -cat-dash
)
expect_output dash "$dash_output" 'dash-leading file cat'
