#!/bin/sh
set -eu

test_tmp=$(mktemp -d "${TMPDIR:-/tmp}/dud-test-musl-cc.XXXXXX")

cleanup_test_tmp() {
    rm -rf "$test_tmp"
}

trap cleanup_test_tmp EXIT HUP INT TERM

return_0_c="$test_tmp/return-0.c"
return_0="$test_tmp/return-0"

cat >"$return_0_c" <<'EOF'
int main(void) {
    return 0;
}
EOF

./bin/musl-cc "$return_0_c" -o "$return_0"
"$return_0"
