#!/bin/sh
set -eu

# we expect no args
if [ "$#" -ne 0 ]; then
    printf '%s\n' 'usage: ./check' >&2
    exit 2
fi

# make scratch dir
tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/dud-check.XXXXXX")
cleanup_tmp() { rm -rf "$tmp_dir"; }
trap cleanup_tmp EXIT HUP INT TERM

# ensure .bin dir
mkdir -p .bin

# ./shellcheck-all
shellcheck_dir=.bin/shellcheck-v0.11.0.linux.x86_64
shellcheck=$shellcheck_dir/shellcheck-v0.11.0/shellcheck
if [ ! -x "$shellcheck" ]; then
    mkdir "$tmp_dir/shellcheck"
    tar -xJf vendor/shellcheck-v0.11.0.linux.x86_64.tar.xz \
        -C "$tmp_dir/shellcheck"
    rm -rf "$shellcheck_dir"
    mv "$tmp_dir/shellcheck" "$shellcheck_dir"
fi
"$shellcheck" -x -s sh -- ./shellcheck-all
./shellcheck-all

# smoke test a c compiler
smoke_cc() {
    cc=$1
    return_0=$tmp_dir/return-0

    "$cc" -static test/c/return-0.c -o "$return_0"
    "$return_0"
}

# musl_cc
musl_cc_dir=.bin/x86_64-linux-musl-native
musl_cc=$musl_cc_dir/bin/x86_64-linux-musl-gcc
if [ ! -x "$musl_cc" ]; then
    mkdir "$tmp_dir/musl-cc"
    tar -xzf vendor/x86_64-linux-musl-native.tgz -C "$tmp_dir/musl-cc"
    rm -rf "$musl_cc_dir"
    mv "$tmp_dir/musl-cc/x86_64-linux-musl-native" "$musl_cc_dir"
fi
musl_cc() {
    "$musl_cc" \
        -std=c11 \
        -Wall \
        -Wextra \
        -Wpedantic \
        -Werror \
        -Wfatal-errors \
        -Wmissing-prototypes \
        -Wstrict-prototypes \
        -Wold-style-definition \
        -static \
        "$@"
}
smoke_cc musl_cc

# tcc1
tcc1=.bin/dud-tcc/tcc1
if [ ! -x "$tcc1" ]; then
    ./src/dud-tcc/build
fi
smoke_cc "$tcc1"

# build + test

musl_cc src/expect/main.c -o .bin/expect
./test/expect/main

musl_cc src/ctok/main.c -o .bin/ctok
./test/ctok/main

musl_cc \
    src/dud-sh/main.c \
    src/dud-sh/action.c \
    src/clib/io.c \
    src/clib/str.c \
    src/clib/exit.c \
    src/dud-sh/fopen_argv.c \
    src/dud-sh/lex.c \
    -o .bin/dud-sh
./test/dud-sh/main
