#!/bin/sh
set -eu

# `sh -n` on scripts before we have a working shellcheck

./bin/for-each-sh-script sh ./bin/sh-n

# unpack the goodies

./bin/cache-vendored

# lint shell

./bin/shellcheck-all

# musl-cc smoke test

musl_cc=\
'.cache/vendor/musl-cc/x86_64-linux-musl-native/'\
'x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc'

cc_strict() {
    "$musl_cc" \
        -std=c11 \
        -Wall \
        -Wextra \
        -Wpedantic \
        -Werror \
        -Wmissing-prototypes \
        -Wstrict-prototypes \
        -Wold-style-definition \
        "$@"
}

return_0_c='.cache/test/return-0.c'
return_0='.cache/test/return-0'

mkdir -p "$(dirname "$return_0")"
cat >"$return_0_c" <<'EOF'
int main(void) {
    return 0;
}
EOF

cc_strict -static "$return_0_c" -o "$return_0"
"$return_0"

# build dud-sh

cc_strict \
    -static \
    src/main.c \
    src/action.c \
    src/dud/io.c \
    src/dud/str.c \
    src/dud/exit.c \
    src/fopen_argv.c \
    src/lex.c \
    -o .cache/dud-sh

# dud-sh smoke tests

# shellcheck disable=SC1091
. ./lib/expect.sh

expect_error 2 '???' .cache/dud-sh
expect_error 2 '???' .cache/dud-sh --to-lexer-symbols
expect_error 2 '???' .cache/dud-sh -c ':'
expect_error 1 '!!!' .cache/dud-sh --to-lexer-symbols .cache/test/no-such-file

./test/test-to-lexer-symbols
