#!/bin/sh
set -eu

# `sh -n` on scripts before we have a working shellcheck
#
# NOTE we purposly check a number of fixed scripts
# by hand first: those called downstream of ./bin/for-each-sh-script itself
#
# BUG maintainging this list by hand is gross, 
# but is the right thing to do, I think

sh -n ./bin/for-each-sh-script
sh -n ./bin/has-sh-shebang
sh -n ./bin/run-script-for-path-in-find
sh -n ./bin/run-script-foreach
sh -n ./bin/sh-n
./bin/for-each-sh-script sh ./bin/sh-n

# unpack the goodies

./bin/cache-vendored

# lint shell

./bin/shellcheck-all

# musl-cc smoke test

./test/test-musl-cc

# build dud-sh

mkdir -p .cache

./bin/musl-cc \
    src/main.c \
    src/action.c \
    src/clib/io.c \
    src/clib/str.c \
    src/clib/exit.c \
    src/fopen_argv.c \
    src/lex.c \
    -o .cache/dud-sh

# dud-sh smoke tests

check_tmp=$(mktemp -d "${TMPDIR:-/tmp}/dud-check.XXXXXX")

cleanup_check_tmp() {
    rm -rf "$check_tmp"
}

trap cleanup_check_tmp EXIT HUP INT TERM

. ./test/expect.sh

expect_error 2 '???' .cache/dud-sh
expect_error 2 '???' .cache/dud-sh --to-lexer-symbols
expect_error 2 '???' .cache/dud-sh -c ':'
expect_error 1 '!!!' .cache/dud-sh --to-lexer-symbols "$check_tmp/no-such-file"

./test/test-to-lexer-symbols
