#!/bin/sh
set -eu

usage() {
    printf '%s\n' 'usage: ./init [--clean]' >&2
}

if [ "$#" -eq 1 ] && [ "$1" = '--clean' ]; then
    rm -rf .init
    exit 0
fi

# we expect no args
if [ "$#" -ne 0 ]; then
    usage
    exit 2
fi

# ensure .init dir
mkdir -p .init

./00-shellcheck/init
./01-smoke-cc/init
./02-musl-cc/init

./03-musl-tcc/init

./src/expect/init
./src/ctok/init
./src/dud-sh/init
