#!/bin/sh
set -eu

usage() {
    printf '%s\n' 'usage: ./init [--clean]' >&2
}

if [ "$#" -eq 1 ] && [ "$1" = '--clean' ]; then
    rm -rf .init
    exit 0
fi

# we expect no args
if [ "$#" -ne 0 ]; then
    usage
    exit 2
fi

# make scratch dir
tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/dud-init.XXXXXX")
cleanup_tmp() { rm -rf "$tmp_dir"; }
trap cleanup_tmp EXIT HUP INT TERM

# ensure .init dir
mkdir -p .init

./00-shellcheck/init

# helper to smoke test a c compiler
smoke_cc() {
    cc=$1
    return_0=$tmp_dir/return-0

    "$cc" -static src/return-0/main.c -o "$return_0"
    "$return_0"
}

# bootstrap musl-cc
musl_dir=.init/x86_64-linux-musl-native
if [ ! -x "$musl_dir/bin/x86_64-linux-musl-gcc" ]; then
    mkdir "$tmp_dir/musl-exe"
    tar -xzf vendor/x86_64-linux-musl-native.tgz -C "$tmp_dir/musl-exe"
    rm -rf "$musl_dir"
    mv "$tmp_dir/musl-exe/x86_64-linux-musl-native" "$musl_dir"
fi
smoke_cc ./bin/musl-cc

# bootstrap dud-tcc
tcc_dir=.init/bootstrap-tcc
tcc_stamp=src/dud-tcc/.stamp
tcc=$tcc_dir/tcc
if [ ! -d "$tcc_dir" ] ||
    [ ! -x "$tcc" ] ||
    [ "$tcc_stamp" -nt "$tcc_dir" ]
then
    ./src/dud-tcc/init
fi
smoke_cc ./bin/dud-tcc

# init
./src/init ./bin/musl-cc
