#!/bin/sh
set -eu

usage() {
    printf '%s\n' 'usage: ./runme' >&2
}

if [ "$#" -ne 0 ]; then
    usage
    exit 2
fi

mkdir -p .dud

./00-shellcheck/runme
./01-smoke-cc/runme
./02-musl-cc/runme
./03-musl-tcc/runme
./04-expect/runme
