#!/bin/sh
set -eu

allow_curl=false
for arg in "$@"; do
    if [ "$arg" = "--allow-curl" ]; then
        allow_curl=true
        break
    fi
done

. ./lib/set-dud-tmp.sh
. ./lib/ensure-dud-tmp-dir.sh

MUSL_CC_TARBALL="$dud_tmp/x86_64-linux-musl-cross.tgz"
export MUSL_CC_TARBALL

mock_curl=./bin/mock-curl

mock_curl_calls="$dud_tmp/mock-curl-calls"
export mock_curl_calls
: >"$mock_curl_calls"

sh -n steps/0000-fetch-musl-cc
./steps/0000-fetch-musl-cc "$mock_curl"
test "$(wc -l <"$mock_curl_calls")" -eq 1
test -e "$MUSL_CC_TARBALL"

./steps/0000-fetch-musl-cc "$mock_curl"
test "$(wc -l <"$mock_curl_calls")" -eq 1

unset mock_curl_calls
rm -f "$MUSL_CC_TARBALL"

if [ "$allow_curl" = true ]; then
    ./steps/0000-fetch-musl-cc 'curl'
    ./bin/verify-musl-cc-tarball
    tar -tzf "$MUSL_CC_TARBALL" >/dev/null
fi
