#!/bin/sh
set -eu

usage() {
    printf '%s\n' \
        'usage: ./src/ctok/build CC' \
        'usage: ./src/ctok/build --clean' >&2
}

if [ "$#" -eq 1 ] && [ "$1" = '--clean' ]; then
    rm -f .bin/ctok
    exit 0
fi

if [ "$#" -ne 1 ]; then
    usage
    exit 2
fi

cc=$1

mkdir -p .bin
"$cc" src/ctok/main.c -o .bin/ctok
./src/ctok/test/main
