#!/bin/sh
set -eu

usage() {
    printf '%s\n' \
        'usage: ./src/ctok/init CC' \
        'usage: ./src/ctok/init --clean' >&2
}

if [ "$#" -eq 1 ] && [ "$1" = '--clean' ]; then
    rm -f .init/ctok
    exit 0
fi

if [ "$#" -ne 1 ]; then
    usage
    exit 2
fi

cc=$1

mkdir -p .init
"$cc" src/ctok/main.c -o .init/ctok
./src/ctok/test/main
