#!/bin/sh
set -eu

usage() {
    printf '%s\n' 'usage: ./src/ctok/init' >&2
}

if [ "$#" -ne 0 ]; then
    usage
    exit 2
fi

mkdir -p .init
.init/musl-cc src/ctok/main.c -o .init/ctok
./src/ctok/test/main
