#!/bin/sh
set -eu

usage() {
    printf '%s\n' 'usage: ./05-ctok/init' >&2
}

if [ "$#" -ne 0 ]; then
    usage
    exit 2
fi

mkdir -p .init
.init/musl-cc -static -std=c11 -Wfatal-errors 05-ctok/main.c -o .init/ctok
./05-ctok/test/main
