#!/bin/sh
set -eu

usage() {
    printf '%s\n' 'usage: ./src/expect/init CC' >&2
}

if [ "$#" -ne 1 ]; then
    usage
    exit 2
fi

cc=$1

mkdir -p .init
"$cc" src/expect/main.c -o .init/expect
./src/expect/test/main
