#!/bin/sh
set -eu

usage() {
    printf '%s\n' 'usage: ./src/expect/init' >&2
}

if [ "$#" -ne 0 ]; then
    usage
    exit 2
fi

mkdir -p .init
.init/musl-cc src/expect/main.c -o .init/expect
./src/expect/test/main
