#!/bin/sh
set -eu

usage() {
    printf '%s\n' 'usage: ./src/dud-sh/init' >&2
}

if [ "$#" -ne 0 ]; then
    usage
    exit 2
fi

mkdir -p .init
.init/musl-cc \
    src/dud-sh/main.c \
    src/dud-sh/action.c \
    src/dud-sh/clib/io.c \
    src/dud-sh/clib/str.c \
    src/dud-sh/clib/exit.c \
    src/dud-sh/fopen_argv.c \
    src/dud-sh/lex.c \
    -o .init/dud-sh
./src/dud-sh/test/main
