#!/bin/sh
set -eu

usage() {
    printf '%s\n' 'usage: ./src/dud-sh/init CC' >&2
}

if [ "$#" -ne 1 ]; then
    usage
    exit 2
fi

cc=$1

mkdir -p .init
"$cc" \
    src/dud-sh/main.c \
    src/dud-sh/action.c \
    src/clib/io.c \
    src/clib/str.c \
    src/clib/exit.c \
    src/dud-sh/fopen_argv.c \
    src/dud-sh/lex.c \
    -o .init/dud-sh
./src/dud-sh/test/main
