#!/bin/sh
set -eu

usage() {
    printf '%s\n' \
        'usage: ./src/dud-sh/init CC' \
        'usage: ./src/dud-sh/init --clean' >&2
}

if [ "$#" -eq 1 ] && [ "$1" = '--clean' ]; then
    rm -f .bin/dud-sh
    exit 0
fi

if [ "$#" -ne 1 ]; then
    usage
    exit 2
fi

cc=$1

mkdir -p .bin
"$cc" \
    src/dud-sh/main.c \
    src/dud-sh/action.c \
    src/clib/io.c \
    src/clib/str.c \
    src/clib/exit.c \
    src/dud-sh/fopen_argv.c \
    src/dud-sh/lex.c \
    -o .bin/dud-sh
./src/dud-sh/test/main
