#!/bin/sh
set -eu

usage() {
    printf '%s\n' 'usage: ./04-expect/init' >&2
}

if [ "$#" -ne 0 ]; then
    usage
    exit 2
fi

mkdir -p .init
.init/musl-cc 04-expect/main.c -o .init/expect
./04-expect/test/main
