#!/bin/sh
set -eu

usage() {
    printf '%s\n' 'usage: ./04-expect/init' >&2
}

if [ "$#" -ne 0 ]; then
    usage
    exit 2
fi

mkdir -p .init

if [ ! -x .init/smoke-cc ]; then
    ./01-smoke-cc/init
fi

if [ ! -x .init/musl-cc ] ||
    [ ! -x .init/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc ]
then
    ./02-musl-cc/init
fi

if [ ! -x .init/musl-tcc/tcc ] ||
    [ 03-musl-tcc/.stamp -nt .init/musl-tcc ]
then
    ./03-musl-tcc/init
fi

.init/musl-tcc/tcc \
    -static \
    -std=c11 \
    -Wall \
    -Wextra \
    -Wpedantic \
    -Werror \
    -Wmissing-prototypes \
    -Wstrict-prototypes \
    -Wold-style-definition \
    04-expect/main.c \
    -o .init/expect
./04-expect/test/main

.init/musl-cc -static -std=c11 -Wfatal-errors 04-expect/main.c -o .init/expect
./04-expect/test/main
