#!/bin/sh
set -eu

usage() {
    printf '%s\n' 'usage: ./06-dud-sh/init' >&2
}

if [ "$#" -ne 0 ]; then
    usage
    exit 2
fi

mkdir -p .init
.init/musl-cc \
    -static \
    -std=c11 \
    -Wfatal-errors \
    06-dud-sh/main.c \
    06-dud-sh/action.c \
    06-dud-sh/clib/io.c \
    06-dud-sh/clib/str.c \
    06-dud-sh/clib/exit.c \
    06-dud-sh/fopen_argv.c \
    06-dud-sh/lex.c \
    -o .init/dud-sh
./06-dud-sh/test/main
